import numpy as np

print("\n------Dot Product------\n")  # only  (n,m) * (m,k) = (n,k)
x = np.random.rand(2, 5)
y = np.zeros((1, 2))
y = np.random.rand(5, 3)
z = x.dot(y)
print(x, "\n----\n", y, "\n----\n", z)
print("\n------Cross------\n")
x = np.random.rand(3, 3)
y = np.zeros((1, 2))
y = np.random.rand(3, 3)
z = np.cross(x, y)
print(x, "\n----\n", y, "\n----\n", z)
print("\n------Sum------\n")
x = np.random.rand(1, 5)
y = np.zeros((1, 2))
y = np.random.rand(5, 3)
z = x.dot(y)
print(x, "\n----\n", y, "\n----\n", z, "\n Sum = %.2f" % np.sum(z) )
